ArtGallery/src/Entity/ArtItems.php
<?php

namespace App\Entity;

use App\Repository\ArtItemsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArtItemsRepository::class)]
class ArtItems
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $name = null;

    #[ORM\Column(length: 30)]
    private ?string $artist_first_name = null;

    #[ORM\Column(length: 30)]
    private ?string $artist_last_name = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $production_date = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2)]
    private ?string $price = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getArtistFirstName(): ?string
    {
        return $this->artist_first_name;
    }

    public function setArtistFirstName(string $artist_first_name): static
    {
        $this->artist_first_name = $artist_first_name;

        return $this;
    }

    public function getArtistLastName(): ?string
    {
        return $this->artist_last_name;
    }

    public function setArtistLastName(string $artist_last_name): static
    {
        $this->artist_last_name = $artist_last_name;

        return $this;
    }

    public function getProductionDate(): ?\DateTimeInterface
    {
        return $this->production_date;
    }

    public function setProductionDate(\DateTimeInterface $production_date): static
    {
        $this->production_date = $production_date;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): static
    {
        $this->price = $price;

        return $this;
    }
}

ArtGallery/src/Form/ArtItemsType.php
<?php

namespace App\Form;

use App\Entity\ArtItems;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArtItemsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('artist_first_name')
            ->add('artist_last_name')
            ->add('production_date')
            ->add('image')
            ->add('price')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => ArtItems::class,
        ]);
    }
}

ArtGallery/src/Controller/ArtItemsController.php
<?php

namespace App\Controller;

use App\Entity\ArtItems;
use App\Form\ArtItemsType;
use App\Repository\ArtItemsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/art')]
class ArtItemsController extends AbstractController
{
    #[Route('/', name: 'app_art_items_index', methods: ['GET'])]
    public function index(ArtItemsRepository $artItemsRepository): Response
    {
        return $this->render('art_items/index.html.twig', [
            'art_items' => $artItemsRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_art_items_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $artItem = new ArtItems();
        $form = $this->createForm(ArtItemsType::class, $artItem);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($artItem);
            $entityManager->flush();

            return $this->redirectToRoute('app_art_items_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('art_items/new.html.twig', [
            'art_item' => $artItem,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_art_items_show', methods: ['GET'])]
    public function show(ArtItems $artItem): Response
    {
        return $this->render('art_items/show.html.twig', [
            'art_item' => $artItem,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_art_items_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, ArtItems $artItem, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ArtItemsType::class, $artItem);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_art_items_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('art_items/edit.html.twig', [
            'art_item' => $artItem,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_art_items_delete', methods: ['POST'])]
    public function delete(Request $request, ArtItems $artItem, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$artItem->getId(), $request->request->get('_token'))) {
            $entityManager->remove($artItem);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_art_items_index', [], Response::HTTP_SEE_OTHER);
    }
}

ArtGallery/templates/art_items/_delete_form.html.twig
<form method="post" action="{{ path('app_art_items_delete', {'id': art_item.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');" class="d-inline">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ art_item.id) }}">
    <button class="border border-dark link-dark text-decoration-none link-opacity-75 link-opacity-100-hover shadow bg-light" style="padding: 3px;">Delete</button>
</form>

ArtGallery/templates/art_items/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

ArtGallery/templates/art_items/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit ArtItems{% endblock %}

{% block body %}
    <h1>Edit ArtItems</h1>

    {{ include('art_items/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_art_items_index') }}">back to list</a>

    {{ include('art_items/_delete_form.html.twig') }}
{% endblock %}

ArtGallery/templates/art_items/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gallery{% endblock %}

{% block body %}
    <h1>Gallery</h1>
    <div class="">
        {% for art_item in art_items %}
            <div class="d-flex justify-content-center gap-3 my-5">
                <div class="d-flex flex-column justify-content-end" style="width: 350px;">
                    <div class="p-2 border border-dark shadow">
                        <table class="table">
                            <tbody>
                            <tr>
                                <th>Title:</th>
                                <td>{{ art_item.name }}</td>
                            </tr>
                            <tr>
                                <th>Artist:</th>
                                <td>{{ art_item.artistFirstName }} {{ art_item.artistLastName }}</td>
                            </tr>

                            {% if (is_granted('IS_AUTHENTICATED_FULLY')) %}
                                <tr>
                                    <td colspan="2" class="text-center">
                                        <a href="{{ path('app_art_items_show', {'id': art_item.id}) }}" class="border border-dark p-1 link-dark text-decoration-none link-opacity-75 link-opacity-100-hover shadow">show details</a>
                                        {% if (is_granted('ROLE_ADMIN')) %}
                                            <a href="{{ path('app_art_items_edit', {'id': art_item.id}) }}" class="border border-dark p-1 link-dark text-decoration-none link-opacity-75 link-opacity-100-hover shadow">edit</a>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endif %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="d-flex">
                    <div class="p-3 border border-dark shadow">
                        <img src="{{ art_item.image }}" alt="image of {{ art_item.id }}" height="500px">
                    </div>
                </div>
            </div>
        {% else %}
            <p>no records found</p>
        {% endfor %}
    </div>

    {% if (is_granted('ROLE_ADMIN')) %}
        <a href="{{ path('app_art_items_new') }}" class="border border-dark p-3 link-dark text-decoration-none link-opacity-75 link-opacity-100-hover shadow">Create new</a>
    {% endif %}
    <div class="mt-5"> </div>
{% endblock %}

ArtGallery/templates/art_items/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New ArtItems{% endblock %}

{% block body %}
    <h1>Create new ArtItems</h1>

    {{ include('art_items/_form.html.twig') }}

    <a href="{{ path('app_art_items_index') }}">back to list</a>
{% endblock %}

ArtGallery/templates/art_items/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Details{% endblock %}

{% block body %}
    <h3>{{ art_item.name }} by {{ art_item.artistFirstName }} {{ art_item.artistLastName }}</h3>
    <div class="">
        <div class="d-flex justify-content-center gap-3 my-5">

            <div class="d-flex">
                <div class="p-3 border border-dark shadow">
                    <img src="{{ art_item.image }}" alt="image of {{ art_item.id }}" height="500px">
                </div>
            </div>

            <div class="d-flex flex-column justify-content-end" style="width: 350px;">
                <div class="p-2 border border-dark shadow">
                    <table class="table">
                        <tbody>
                            <tr>
                                <th>Title:</th>
                                <td>{{ art_item.name }}</td>
                            </tr>
                            <tr>
                                <th>Artist:</th>
                                <td>{{ art_item.artistFirstName }} {{ art_item.artistLastName }}</td>
                            </tr>
                            <tr>
                                <th>Production year:</th>
                                <td>{{ art_item.productionDate ? art_item.productionDate|date('Y') : '' }}</td>
                            </tr>
                            <tr>
                                <th>Price</th>
                                <td>{{ art_item.price | number_format(2, ',', '.') ~ '€' }}</td>
                            </tr>
                            <tr>
                                <td colspan="2" class="text-center">
                                    <a href="{{ path('app_art_items_index') }}" class="border border-dark p-1 link-dark text-decoration-none link-opacity-75 link-opacity-100-hover shadow">back to list</a>
                                    {% if (is_granted('ROLE_ADMIN')) %}
                                        <a href="{{ path('app_art_items_edit', {'id': art_item.id}) }}" class="border border-dark p-1 link-dark text-decoration-none link-opacity-75 link-opacity-100-hover shadow">edit</a>
                                        <span>{{ include('art_items/_delete_form.html.twig') }}</span>
                                    {% endif %}
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </div>

    <div class="mt-5"> </div>
{% endblock %}