ArtGallery/src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 30)]
    private ?string $first_name = null;

    #[ORM\Column(length: 30)]
    private ?string $last_name = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }
}

ArtGallery/src/Controller/User2Controller.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/user')]
class User2Controller extends AbstractController
{
    #[Route('/', name: 'app_user2_index', methods: ['GET'])]
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('user2/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_user2_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('app_user2_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('user2/new.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_user2_show', methods: ['GET'])]
    public function show(User $user): Response
    {
        return $this->render('user2/show.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_user2_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, User $user, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_user2_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('user2/edit.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_user2_delete', methods: ['POST'])]
    public function delete(Request $request, User $user, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $entityManager->remove($user);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_user2_index', [], Response::HTTP_SEE_OTHER);
    }
}

ArtGallery/templates/user2/_delete_form.html.twig
<form method="post" action="{{ path('app_user2_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');" class="d-inline">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

ArtGallery/templates/user2/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-warning d-inline">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

ArtGallery/templates/user2/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block body %}
    {% if (is_granted('ROLE_ADMIN') == false) %}
        {% set redirectUrl = path('app_art_items_index') %}
        <script>
            window.location.href = "{{ redirectUrl }}";
        </script>
    {% endif %}
    <h1>Edit User</h1>

    {{ include('user2/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_user2_index') }}" class="btn btn-secondary">back to list</a>

    {{ include('user2/_delete_form.html.twig') }}

{% endblock %}

ArtGallery/templates/user2/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}

{% block body %}
    {% if (is_granted('ROLE_ADMIN') == false) %}
        {% set redirectUrl = path('app_art_items_index') %}
        <script>
            window.location.href = "{{ redirectUrl }}";
        </script>
    {% endif %}
    <h1>Users list</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Email</th>
                <th>Role</th>
                <th>First name</th>
                <th>Last name</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.email }}</td>
                <td>{{ ( user.roles ? user.roles|json_encode : '' ) == '["ROLE_ADMIN","ROLE_USER"]' ? "Admin" : "User" }}</td>
                <td>{{ user.firstName }}</td>
                <td>{{ user.lastName }}</td>
                <td>
                    <a href="{{ path('app_user2_show', {'id': user.id}) }}" class="btn btn-secondary">show</a>
                    <a href="{{ path('app_user2_edit', {'id': user.id}) }}" class="btn btn-secondary">edit</a>
                    {{ include('user2/_delete_form.html.twig') }}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

ArtGallery/templates/user2/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
    {% if (is_granted('ROLE_ADMIN') == false) %}
        {% set redirectUrl = path('app_art_items_index') %}
        <script>
            window.location.href = "{{ redirectUrl }}";
        </script>
    {% endif %}
    <h1>Create new User</h1>

    {{ include('user2/_form.html.twig') }}

    <a href="{{ path('app_user2_index') }}">back to list</a>
{% endblock %}

ArtGallery/templates/user2/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
    {% if (is_granted('ROLE_ADMIN') == false) %}
        {% set redirectUrl = path('app_art_items_index') %}
        <script>
            window.location.href = "{{ redirectUrl }}";
        </script>
    {% endif %}
    <h1>User</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>Role</th>
                <td>{{ ( user.roles ? user.roles|json_encode : '' ) == '["ROLE_ADMIN","ROLE_USER"]' ? "Admin" : "User" }}</td>
            </tr>
            <tr>
                <th>First name</th>
                <td>{{ user.firstName }}</td>
            </tr>
            <tr>
                <th>Last name</th>
                <td>{{ user.lastName }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_user2_index') }}" class="btn btn-secondary">back to list</a>

    <a href="{{ path('app_user2_edit', {'id': user.id}) }}" class="btn btn-warning">edit</a>

    {{ include('user2/_delete_form.html.twig') }}
{% endblock %}